/* generated by mapgen - do not edit */

#ifndef MTBIT_H
#define MTBIT_H

#define BIT_TRACKING_ID 9
#define BIT_POSITION_X 5
#define BIT_POSITION_Y 6
#define BIT_TOUCH_MAJOR 0
#define BIT_TOUCH_MINOR 1
#define BIT_WIDTH_MAJOR 2
#define BIT_WIDTH_MINOR 3

#endif
